name: 'Execução Manual'

on: 
  workflow_dispatch:

jobs: 
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
        
      - name: Instalando Dependencias
        run: yarn install --frozen-lockfile

      - name: Instalando Browsers do Playwright
        run: yarn playwright install --with-deps

      - name: Executando testes E2E
        run: yarn run 2e2
